### PR TITLE
Batching with array

### LINKED ISSUE #516: electrum rpc batch request not working
I tried to send an electrum rpc batch request for blockchain.transaction.get with several txid and I don't think I ever got a response back.

Either is not implemented at all or there's a bug. Works on original electrs, electrumx and fulcrum.
Example request that failed:

[{"jsonrpc":"2.0","id":"2","method":"blockchain.transaction.get","params":["a0d1ec3d3b821c86f36dcea5767b92e952c7337e1ad2b591467d9c9e61e70b06"]},{"jsonrpc":"2.0","id":"2-1","method":"blockchain.transaction.get","params":["83b54434a7dd45db6e06c519381a57dda30e8173c15a8232fa3dd9216cbe4940"]}]

For example in bash
```
echo '[{"jsonrpc":"2.0","id":"2","method":"blockchain.transaction.get","params":["a0d1ec3d3b821c86f36dcea5767b92e952c7337e1ad2b591467d9c9e61e70b06"]},{"jsonrpc":"2.0","id":"2","method":"blockchain.transaction.get","params":["83b54434a7dd45db6e06c519381a57dda30e8173c15a8232fa3dd9216cbe4940"]}]' | nc bitcoin.aranguren.org 50001
``` 

you get
```
[{"id":"2","jsonrpc":"2.0","result":"01000000000101ec04e0ff2e79933145aaf9e4965908d21e2fd1962401b688b44c4228d3031ff70100000000ffffffff0300e1f50500000000220020b2014722cac7f707df13577d1604519cd642e8ccbda1da36cf42f628d33aa3db93ae9d0000000000160014dc6bf86354105de2fcd9868a2b0376d6731cb92f78c10900000000001600141ba5f0f9bdca2230a2ec1a057730cb299142461c0248304502210097a1679ddc306a4c524508db2faa121fa6e65286941f5426bb2f0575b60e06c702202ab74bc9701682880f891226dd94e1198604f7a3a5b512535b7b74845520fb0d012102174ee672429ff94304321cdae1fc1e487edf658b34bd1d36da03761658a2bb0900000000"},{"id":"2","jsonrpc":"2.0","result":"01000000000102cbdb01e3cd3ce618d005d9feb2e4836b1642bed26e5af2362c5b7cbac7ebe9ce0100000000ffffffff48b586904f328cc26a3cd1460f44323f522e382cf7ac15313228bd640e4601d00100000000ffffffff0200a3e111000000001600142baf69a6e9726896e2dfa8276f3896e470637bd35db8dc1900000000220020f98feeabd03d66869199e8378eccc3c9e750db5f714a7b267805a6dc81bbe7050400483045022100d5fd46fe8f9fd345753d37efed67978f1b7fa9caff8452e46f1ad8df2671f66802205400515475f818662b4208f0bb82762192826394d0510339260b292ad394ac6d0148304502210087a9b498decece4201c686371643e894d02e367c4555f5c3101f9c793d4b385c022028f334c3cad645b365ea9a4a6634fa641c6e2752d332b50885c8f99d55cf21c101695221033ad6b7e0ff538ced53e678772e9ef900bd6c42a1ab2b5ac9fef4422f08cb5a9a21037eba9a31559eff1a4b5e0a77558ba450a24038c3a2d761d3d57807a4241cdea52103f751c8926da63a4f4f1f3b92c932a9ce5c48d47035395ee36c4d902ffd43e7fc53ae0400483045022100b701879cf231cf7409a752ee653fe81d591fe4f3a75a9b6b1fc7de9d70b45d5602203ee2efa698ad738ac1ce9e3860806dbb39dd4b086ecb88595f22aba3b82933db0147304402207ecfed58b86298e7383b5964845a60e6d118ad66286963cc25e7643d6fe9491602202fbef453f246db720e7b813fa805a8729a97dcc43a1760aaf4d7bc1e385e02dc01695221033ad6b7e0ff538ced53e678772e9ef900bd6c42a1ab2b5ac9fef4422f08cb5a9a21037eba9a31559eff1a4b5e0a77558ba450a24038c3a2d761d3d57807a4241cdea52103f751c8926da63a4f4f1f3b92c932a9ce5c48d47035395ee36c4d902ffd43e7fc53ae00000000"}]

```

with
```
echo '[{"jsonrpc":"2.0","id":"2","method":"blockchain.transaction.get","params":["a0d1ec3d3b821c86f36dcea5767b92e952c7337e1ad2b591467d9c9e61e70b06"]},{"jsonrpc":"2.0","id":"2","method":"blockchain.transaction.get","params":["83b54434a7dd45db6e06c519381a57dda30e8173c15a8232fa3dd9216cbe4940"]}]' | nc electrum.blockstream.info  50001
```

we get nothing (it just returns)

for other non batched requests it works as expected
```
echo '{"jsonrpc": "2.0", "method": "server.version", "id": 0}' | nc electrum.blockstream.info 50001
```
```
{"id":0,"jsonrpc":"2.0","result":["electrs-esplora 0.4.1","1.4"]}
```

### PR DESCRIPTION
**Pull request by RCasatta**
Currently electrs support batching by separating requests via new lines, however, other impls support it also via json array  as explained in the cited issue. This add support for batching requests via json array

close https://github.com/Blockstream/esplora/issues/516

### CODE REVIEW

File: src/electrum/server.rs [hunk 1]
```diff
@@ -601,6 +569,55 @@ impl Connection {
         }
     }
 
+    fn handle_value(
+        &mut self,
+        cmd: Value,
+        empty_params: &Value,
+        start_time: Instant,
```
Comment (shesek) [inline src/electrum/server.rs]: Shouldn't the start_time start ticking separately for each `handle_value` call?

Comment (RCasatta) [reply src/electrum/server.rs]: yes, it makes sense. Done in b8f4524cdbe8f280da9fd87d2a4ac136f630a30f

**Comment by shesek** [comment]
Should we limit the number of requests per batch?

File: tests/electrum.rs [hunk 2]
```diff
@@ -137,3 +140,44 @@ fn test_electrum() -> Result<()> {
 
     Ok(())
 }
+
+/// Test the Electrum RPC server using an headless Electrum wallet
```
Comment (shesek) [inline tests/electrum.rs]: The comment here should be updated, "using a raw TCP socket" or something similar

**Comment by RCasatta** [comment]
> Should we limit the number of requests per batch?

Do we have limits for "new-line separated" batch requests? Is it different here? How much do you propose as the limit here?

**Comment by shesek** [comment]
> Do we have limits for "new-line separated" batch requests? Is it different here?

We don't, but it is different here. New-lines separated requests are streamed, and individual responses are sent as they become available. We only hold up to 10 pending requests in the queue, then block and stop reading from the TCP socket until a pending request gets processed to free room (a bounded `mpsc::sync_channel`).

With array batching all the requests and all the response has to be buffered in-memory at once, which could use significant resources and be a DoS vector if there are no limits in place.

**Comment by RCasatta** [comment]
> How much do you propose as the limit here

Do you think we can afford 20 as the limit for batch requests? I think it's common number because is used as gap limit...

**Comment by shesek** [comment]
20 seems fine, yes :+1:

However it seems the tests are failing. The failure isn't directly related to the batching but to the TestRunner used to test it.

**Comment by RCasatta** [comment]
I didn't realize locally because i launched the test singularly, I think we don't support having multiple concurrent tests.
My solution is to make the test ignored by default and test it specifically.

File: tests/electrum.rs (hunk 2 above)
Comment (RCasatta) [reply tests/electrum.rs]: Done in 250fb9b33d990822f06c6b1ef552c0ebd137e93a

**Comment by RCasatta** [comment]
Rebased on `new-index` and fixed forgotten comment

**Comment by shesek** [comment]
> I think we don't support having multiple concurrent tests.

I tracked down the cause. It's not specific to the tests, it fails whenever `electrs` is run multiple times in the same process, even if not concurrently.

This appears to happen because the threads sending parallel RPC requests to bitcoind are being reused across different electrs instances. Each RPC thread has a `thread_local` var with a cached `Daemon` instance (and TCP socket). The thread initially initializes a `Daemon` connection to Instance A's bitcoind, then later when the same thread is reused for instance B but the cached connection to A is returned instead - causing the mismatch errors.

If you apply this patch:
```patch
diff --git a/src/daemon.rs b/src/daemon.rs
index 6808907..48498c7 100644
--- a/src/daemon.rs
+++ b/src/daemon.rs
@@ -493,9 +493,9 @@ impl Daemon {
                 // Store a local per-thread Daemon, each with its own TCP connection. These will
                 // get initialized as necessary for the `rpc_threads` pool thread managed by rayon.
                 thread_local!(static DAEMON_INSTANCE: OnceCell<Daemon> = OnceCell::new());
 
                 DAEMON_INSTANCE.with(|daemon| {
-                    daemon
-                        .get_or_init(|| self.retry_reconnect())
-                        .retry_request(&method, &params)
+                    let d = daemon.get_or_init(|| self.retry_reconnect());
+                    debug!("rpc thread {:?} of {} got {}", std::thread::current().id(), self.daemon_dir.display(), d.daemon_dir.display());
+                    d.retry_request(&method, &params)
                 })
             })
         })
```

And run:
```
RUST_LOG=debug cargo test electrum -- --nocapture --test-threads 1 2>&1 | grep 'rpc thread'
```

You'll see:

```
DEBUG rpc thread ThreadId(17) of /tmp/.tmp8eAz3c/regtest got /tmp/.tmp8eAz3c/regtest
...
DEBUG rpc thread ThreadId(17) of /tmp/.tmptlPtvs/regtest got /tmp/.tmp8eAz3c/regtest
```

Note how the second time its trying to get a `Daemon` connected to `tmptlPtvs`, but gets the previous `tmp8eAz3c` instead because it ran on the same thread.

I was expecting the threads not to be reused across electrs instances, because each is using [its own `rayon::ThreadPool`](https://github.com/Blockstream/electrs/blob/38d252537bcc01a4c6ade54961df191bc65aec85/src/daemon.rs#L328-L329). Can't quite figure out what's causing this. Any ideas?

**Comment by RCasatta** [comment]
I am not sure how to handle this...

1) avoid the thread local in testing? 
2) Doing the raw test at the end of `test_electrum` so that not 2 RPC are started
3) Merge this (test ignored, launched singularly) and open an issue

**Review by shesek — DISMISSED** [review]
tACK 250fb9b

Let's merge as-is for now with the new test launched singularly, I'll continue investigating the cause for the thread reuse after that.

**Comment by RCasatta** [comment]
I had to rebase after #128

**Review by philippem — APPROVED** [review]

**Comment by MASIHmirsali65** [comment]
I am the original adoptive father of Bitcoin, please, without any reason or reason, open all the scams and tokens that are related to our IP and block the obstacles. Please get control as soon as possible.
